version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: helpdesk_db
      MYSQL_USER: helpdesk_user
      MYSQL_PASSWORD: helpdesk_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  mysql_data:
